const routes = {
  basic: {
    gidonline: '/',
    new: '/new',
    premieres: '/premieres',
    navigator: '/navigator',
    random: '/random',
    pagination: '/page-',
  },
  genres: {
    genre: '/genre/',
    western: '/genre/western',
    thriller: '/genre/thriller',
    biography: '/genre/biography',
    military: '/genre/military',
    detective: '/genre/detective',
    drama: '/genre/drama',
    documentary: '/genre/documentary',
    history: '/genre/history',
    comedy: '/genre/comedy',
    crime: '/genre/crime',
    melodrama: '/genre/melodrama',
    music: '/genre/music',
    cartoon: '/genre/cartoon',
    adventure: '/genre/adventure',
    family: '/genre/family',
    sport: '/genre/sport',
    serials: '/genre/serials',
    action: '/genre/action',
    horror: '/genre/horror',
    fantasy: '/genre/fantasy',
    fantastic: '/genre/fantastic',
  },
};
export default routes;
